// SDK Version Constants
const LF_X_L_16: string = "LF_X_L16";
const LF_X_L_20: string = "LF_X_L20";
const LF_X_L_17: string = "LF_X_L17";
const HT_8: string = "HT_8_";
const HT_4_ARM: string = "HT_4_Arm_";
const LF_4_Z: string = "LF_4_ZLefu_2023-05-15_V1.0.0";
const HT_4_LEG: string = "HT_4_Leg_";
const HT_4_LEG2: string = "HT_4_Leg2_";
const HT_4_2CHANNEL: string = "HT_4_2Channel_";

export {
  LF_X_L_16,
  LF_X_L_20,
  LF_X_L_17,
  HT_8,
  HT_4_ARM,
  LF_4_Z,
  HT_4_LEG,
  HT_4_LEG2,
  HT_4_2CHANNEL
}
